!=======================================================================
! Generated by  : PSCAD v4.6.3.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  BRK, BRK_STAT
      REAL     V1, V2, V3, Ishort, I30, I20, I12
      REAL     V34, V4, V5, Ibrk

! Internal Variables
      INTEGER  IVD1_1, IVD1_2
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 2
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 11
      IPGB      = NPGB
      NPGB      = NPGB + 12
      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      V1       = STOF(ISTOF + 1)
      V2       = STOF(ISTOF + 2)
      V3       = STOF(ISTOF + 3)
      Ishort   = STOF(ISTOF + 4)
      I30      = STOF(ISTOF + 5)
      I20      = STOF(ISTOF + 6)
      I12      = STOF(ISTOF + 7)
      V34      = STOF(ISTOF + 8)
      V4       = STOF(ISTOF + 9)
      V5       = STOF(ISTOF + 10)
      BRK      = STOI(ISTOI + 1)
      BRK_STAT = STOI(ISTOI + 2)
      Ibrk     = STOF(ISTOF + 11)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         BRK = 0
      ELSE
         BRK = 0
         IF ( TIME .GE. 0.06667 ) BRK = (1-0)
      ENDIF

! 80:[breaker1] Single Phase Breaker 'BRK'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS, (IBRCH+6),1.0e-06,1000000.0,0,NINT(1.0-REAL(&
     &BRK)))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+6),SS))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,189360772,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH+6),SS))
      BRK_STAT = IVD1_1

! 240:[pgb] Output Channel 'BRK_STAT'

      PGB(IPGB+11) = REAL(BRK_STAT)

! 1:[source_1] Single Phase Voltage Source Model 2 'vs'
!  Single Phase AC source: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS, (IBRCH+1),RVD1_4,1,RVD1_1,RVD1_2,RVD1_3)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = V1
      STOF(ISTOF + 2) = V2
      STOF(ISTOF + 3) = V3
      STOF(ISTOF + 4) = Ishort
      STOF(ISTOF + 5) = I30
      STOF(ISTOF + 6) = I20
      STOF(ISTOF + 7) = I12
      STOF(ISTOF + 8) = V34
      STOF(ISTOF + 9) = V4
      STOF(ISTOF + 10) = V5
      STOI(ISTOI + 1) = BRK
      STOI(ISTOI + 2) = BRK_STAT
      STOF(ISTOF + 11) = Ibrk


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_6, NT_7, NT_9
      INTEGER  NT_10

! Control Signals
      REAL     V1, V2, V3, Ishort, I30, I20, I12
      REAL     V34, V4, V5, Ibrk

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 12
      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      V1       = STOF(ISTOF + 1)
      V2       = STOF(ISTOF + 2)
      V3       = STOF(ISTOF + 3)
      Ishort   = STOF(ISTOF + 4)
      I30      = STOF(ISTOF + 5)
      I20      = STOF(ISTOF + 6)
      I12      = STOF(ISTOF + 7)
      V34      = STOF(ISTOF + 8)
      V4       = STOF(ISTOF + 9)
      V5       = STOF(ISTOF + 10)
      Ibrk     = STOF(ISTOF + 11)


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_6  = NODE(INODE + 3)
      NT_7  = NODE(INODE + 4)
      NT_9  = NODE(INODE + 5)
      NT_10 = NODE(INODE + 6)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 20:[voltmetergnd] Voltmeter (Line - Ground) 'V1'
      V1 = EMTDC_VVDC(SS, NT_1, 0)

! 30:[voltmetergnd] Voltmeter (Line - Ground) 'V2'
      V2 = EMTDC_VVDC(SS, NT_2, 0)

! 40:[ammeter] Current Meter 'I12'
      I12 = ( CBR((IBRCH+3), SS))

! 50:[voltmetergnd] Voltmeter (Line - Ground) 'V3'
      V3 = EMTDC_VVDC(SS, NT_9, 0)

! 60:[ammeter] Current Meter 'Ibrk'
      Ibrk = ( CBR((IBRCH+2), SS))

! 70:[voltmeter] Voltmeter (Line - Line) 'V34'
      V34 = EMTDC_VVDC(SS, NT_10, NT_6)

! 80:[breaker1] Single Phase Breaker 'BRK'
! Single phase breaker current
!

! 90:[voltmetergnd] Voltmeter (Line - Ground) 'V4'
      V4 = EMTDC_VVDC(SS, NT_6, 0)

! 100:[pgb] Output Channel 'V1'

      PGB(IPGB+1) = V1

! 110:[voltmetergnd] Voltmeter (Line - Ground) 'V5'
      V5 = EMTDC_VVDC(SS, NT_7, 0)

! 120:[ammeter] Current Meter 'I20'
      I20 = (-CBR((IBRCH+4), SS))

! 130:[ammeter] Current Meter 'I30'
      I30 = (-CBR((IBRCH+5), SS))

! 140:[pgb] Output Channel 'V2'

      PGB(IPGB+2) = V2

! 150:[ammeter] Current Meter 'Ishort'
      Ishort = ( CBR((IBRCH+7), SS))

! 160:[pgb] Output Channel 'V3'

      PGB(IPGB+3) = V3

! 170:[pgb] Output Channel 'V34'

      PGB(IPGB+4) = V34

! 180:[pgb] Output Channel 'V4'

      PGB(IPGB+5) = V4

! 190:[pgb] Output Channel 'V5'

      PGB(IPGB+6) = V5

! 200:[pgb] Output Channel 'Ishort'

      PGB(IPGB+7) = Ishort

! 210:[pgb] Output Channel 'I30'

      PGB(IPGB+8) = I30

! 220:[pgb] Output Channel 'I20'

      PGB(IPGB+9) = I20

! 230:[pgb] Output Channel 'I12'

      PGB(IPGB+10) = I12

! 250:[pgb] Output Channel 'Ibrk'

      PGB(IPGB+12) = Ibrk

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = V1
      STOF(ISTOF + 2) = V2
      STOF(ISTOF + 3) = V3
      STOF(ISTOF + 4) = Ishort
      STOF(ISTOF + 5) = I30
      STOF(ISTOF + 6) = I20
      STOF(ISTOF + 7) = I12
      STOF(ISTOF + 8) = V34
      STOF(ISTOF + 9) = V4
      STOF(ISTOF + 10) = V5
      STOF(ISTOF + 11) = Ibrk


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 80:[breaker1] Single Phase Breaker 'BRK'
      CALL COMPONENT_ID(ICALL_NO,189360772)
      CALL E1PBRKR1_CFG(1.0e-06,1000000.0,0.0)

! 240:[pgb] Output Channel 'BRK_STAT'

! 1:[source_1] Single Phase Voltage Source Model 2 'vs'
      CALL E_1PVSRC_CFG(1,0,6,163.0,60.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1, NT_2, NT_6, NT_7, NT_9
      INTEGER  NT_10

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 9
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_6  = NODE(INODE + 3)
      NT_7  = NODE(INODE + 4)
      NT_9  = NODE(INODE + 5)
      NT_10 = NODE(INODE + 6)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 100:[pgb] Output Channel 'V1'

! 140:[pgb] Output Channel 'V2'

! 160:[pgb] Output Channel 'V3'

! 170:[pgb] Output Channel 'V34'

! 180:[pgb] Output Channel 'V4'

! 190:[pgb] Output Channel 'V5'

! 200:[pgb] Output Channel 'Ishort'

! 210:[pgb] Output Channel 'I30'

! 220:[pgb] Output Channel 'I20'

! 230:[pgb] Output Channel 'I12'

! 250:[pgb] Output Channel 'Ibrk'

      RETURN
      END